In [5]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 


df = pd.read_csv('../data/meningitis.csv')
df = df.drop('casenum', axis=1)
display(df)

,year,month,age,race,sex,dx,priordx,priorrx,wbc,pmn,...,pr2,reds2,whites2,polys2,lymphs2,monos2,others2,sumbands,subset,abm
0,78.0,1.0,4.0,black,female,1.0,0.0,0.0,6.500000,50.0,...,46.0,1.0,47.0,0.0,100.0,0.0,0.0,2.000000,test,1.0
1,78.0,12.0,1.0,black,male,1.0,0.0,0.0,3.700000,62.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.099000,training,1.0
2,78.0,3.0,0.8,black,male,0.0,1.0,1.0,NaN,NaN,...,51.0,335.0,230.0,0.0,100.0,0.0,0.0,NaN,test,NaN
3,78.0,8.0,54.0,black,male,6.0,2.0,0.0,7.500000,73.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.108999,training,1.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,test,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576,70.0,7.0,2.0,black,female,3.0,0.0,0.0,4.900000,57.0,...,NaN,NaN,6.0,0.0,100.0,0.0,0.0,NaN,test,1.0
577,70.0,7.0,23.0,black,male,4.0,0.0,0.0,10.599999,70.0,...,NaN,0.0,332.0,0.0,100.0,0.0,0.0,NaN,training,0.0
578,70.0,8.0,8.0,black,male,4.0,0.0,0.0,15.099999,91.0,...,NaN,NaN,28.0,0.0,100.0,0.0,0.0,NaN,test,0.0
579,70.0,7.0,1.0,black,female,0.0,0.0,1.0,11.599999,53.0,...,22.0,NaN,5.0,0.0,100.0,0.0,0.0,NaN,training,NaN
580,70.0,7.0,13.0,white,male,6.0,2.0,1.0,12.500000,77.0,...,NaN,2.0,0.0,NaN,NaN,NaN,NaN,NaN,test,1.0

In [6]:
# exploring the variables 

for p in df.columns.tolist():
    print(p)

year
month
age
race
sex
dx
priordx
priorrx
wbc
pmn
bands
compns
daysrx
offrx
lptodc
lpgap
morelabs
bloodgl
gl
pr
reds
whites
polys
lymphs
monos
others
gram
culture
cie
bloodclt
bloodgl2
gl2
pr2
reds2
whites2
polys2
lymphs2
monos2
others2
sumbands
subset
abm

In [8]:
df['sumbands']

0      2.000000
1      3.099000
2           NaN
3      5.108999
4           NaN
         ...
576         NaN
577         NaN
578         NaN
579         NaN
580         NaN
Name: sumbands, Length: 581, dtype: float64

In [11]:
# lets start explore our data and understand it 
print(f'observations: {df.shape[0]}\nvariables: {df.shape[1]}')

# lets see missing data for each variable
miss = df.isna().sum().sort_values(ascending=False)
miss = miss[miss > 0]

print('missing variables ')
for index, val in miss.items():
    print(f'{index:10s}: {val:10d}')

observations: 581
variables: 42
missing variables
cie       :        509
morelabs  :        483
bloodgl2  :        459
lpgap     :        438
bloodclt  :        434
sumbands  :        416
lptodc    :        414
offrx     :        409
pr2       :        358
reds2     :        331
daysrx    :        321
others2   :        316
monos2    :        314
gram      :        313
gl2       :        313
lymphs2   :        310
culture   :        307
polys2    :        305
compns    :        295
whites2   :        274
reds      :        271
bloodgl   :        258
pr        :        249
monos     :        165
others    :        164
lymphs    :        162
bands     :        153
pmn       :        146
wbc       :        141
polys     :        132
gl        :        129
priordx   :        113
priorrx   :        108
whites    :        101
race      :         85
dx        :         83
month     :         81
sex       :         81
age       :         81
abm       :         80
year      :         72

# 02 Data Cleaning

## Aim

The aim of this notebook is to create an analysis-ready dataset from the raw meningitis dataset while preserving the original raw data unchanged.

## Raw Data Principle

The original dataset in `data/raw/meningitis.csv` will not be modified. All cleaning decisions will be applied to a copied dataframe and saved as a new file in `data/processed/`.

## Column Selection Decision

The raw dataset contains baseline variables, follow-up variables, treatment-related variables, second lumbar puncture variables, and diagnostic confirmation variables.

For the first analysis, I kept variables that are available at baseline or are clinically relevant for early differentiation between bacterial and viral meningitis.

Variables excluded from the first cleaned dataset include unclear variables, treatment/follow-up variables, second lumbar puncture variables, and diagnostic confirmation variables that may leak the final diagnosis.

## Variables Kept

The following variables were kept:

- `year`
- `month`
- `age`
- `race`
- `sex`
- `priorrx`
- `wbc`
- `pmn`
- `bands`
- `bloodgl`
- `gl`
- `pr`
- `reds`
- `whites`
- `polys`
- `lymphs`
- `monos`
- `others`
- `gram`
- `subset`
- `abm`

## Variables Excluded For The First Analysis

The following variables were excluded from the first cleaned dataset:

- `dx`
- `priordx`
- `compns`
- `daysrx`
- `offrx`
- `lptodc`
- `lpgap`
- `morelabs`
- `culture`
- `cie`
- `bloodclt`
- `bloodgl2`
- `gl2`
- `pr2`
- `reds2`
- `whites2`
- `polys2`
- `lymphs2`
- `monos2`
- `others2`
- `sumbands`

## Rationale

These variables were excluded because they are unclear, treatment-related, follow-up variables, second lumbar puncture measurements, or diagnostic confirmation variables. Since the goal of this project is to evaluate early baseline predictors of bacterial meningitis, including post-baseline or final diagnostic confirmation variables could bias the analysis.

## Column Renaming

Variables were renamed to improve readability while preserving a record of the original names in the data dictionary.

In [13]:
# columns to keep 

columns_to_keep = ["year", "month", "age", "race", "sex", "priorrx",
    "wbc", "pmn", "bands", "bloodgl", "gl", "pr",
    "reds", "whites", "polys", "lymphs", "monos", "others",
    "gram", "subset", "abm"]

# renaming map 
rename_map ={
    "year": "case_year",
    "month": "case_month",
    "age": "age_years",
    "priorrx": "prior_antibiotics",
    "wbc": "blood_wbc_count",
    "pmn": "blood_pmn_percent",
    "bands": "blood_band_percent",
    "bloodgl": "blood_glucose_mg_dl",
    "gl": "csf_glucose_mg_dl",
    "pr": "csf_protein_mg_dl",
    "reds": "csf_rbc_count",
    "whites": "csf_wbc_count",
    "polys": "csf_pmn_percent",
    "lymphs": "csf_lymphocyte_count",
    "monos": "csf_monocyte_value",
    "others": "csf_other_cell_value",
    "gram": "gram_stain_result",
    "subset": "original_subset",
    "abm": "bacterial_meningitis"
}

# conversion 
df_clean = df[columns_to_keep].copy()

df_clean = df_clean.rename(columns=rename_map)
display(df_clean.head())

,case_year,case_month,age_years,race,sex,prior_antibiotics,blood_wbc_count,blood_pmn_percent,blood_band_percent,blood_glucose_mg_dl,...,csf_protein_mg_dl,csf_rbc_count,csf_wbc_count,csf_pmn_percent,csf_lymphocyte_count,csf_monocyte_value,csf_other_cell_value,gram_stain_result,original_subset,bacterial_meningitis
0,78.0,1.0,4.0,black,female,0.0,6.5,50.0,4.0,165.0,...,304.0,440.0,4000.0,100.0,0.0,0.0,0.0,4.0,test,1.0
1,78.0,12.0,1.0,black,male,0.0,3.7,62.0,5.0,150.0,...,NaN,450.0,5490.0,97.0,3.0,0.0,0.0,5.0,training,1.0
2,78.0,3.0,0.8,black,male,1.0,NaN,NaN,NaN,183.0,...,NaN,0.0,4500.0,100.0,0.0,0.0,0.0,0.0,test,NaN
3,78.0,8.0,54.0,black,male,0.0,7.5,73.0,7.0,NaN,...,43.0,27.0,0.0,NaN,NaN,NaN,NaN,0.0,training,1.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,test,0.0

In [14]:
# export the dataset 

df_clean.to_csv('../data/processed/meningitis_clean_v1.csv')